/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEstimateRouteImport } from './routes/api/public/estimate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEstimateRoute = ApiPublicEstimateRouteImport.update({
  id: '/api/public/estimate',
  path: '/api/public/estimate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/estimate': typeof ApiPublicEstimateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/estimate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/estimate'
  id: '__root__' | '/' | '/api/public/estimate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicEstimateRoute: typeof ApiPublicEstimateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/estimate': {
      id: '/api/public/estimate'
      path: '/api/public/estimate'
      fullPath: '/api/public/estimate'
      preLoaderRoute: typeof ApiPublicEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicEstimateRoute: ApiPublicEstimateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
